$env:FLASK_APP=".\api.py"      
$env:FLASK_ENV='development'   
python -m flask run            


set FLASK_APP=api.py
set FLASK_ENV=development
issue 'python -m flask run' command in the folder where API.py resides

E:\Udacity\cd0039-Identity-and-Access-Management\env\Scripts\activate


npm install --global windows-build-tools  


pip freeze

pip install --upgrade MarkupSafe


npm run ng serve

Accidentally seemed to have deleted the period at the start from the below import statements.  

from .database.models import db_drop_and_create_all, setup_db, Drink
from .auth.auth import AuthError, requires_auth

Corrected now and reran the postman collections. 13 test results passed.

7 failed because though auth.py raises Autherror for DELTE/PATCH/POST requests for users, Public and BArista, 500 internal error is returned to front end. Couldn't figure out why.
src.auth.auth.AuthError: ({'code': 'unauthorized', 'description': 'Permission not found'}, 403)